
testdir = 'input/geuvadis/'
model = 'DGN-WB_0.5.db'

```{r}
library(data.table)
library(dplyr)

"%&%" = function(a,b) paste(a,b,sep='')
##pre = '/Users/haky/Downloads/PrediXcan-working-example/'
pre = '/group/im-lab/nas40t2/'
```


## predict expression levels

```{r PREDICTION OF EXPRESSION LEVELS}

## predict_gene_expression.py usage
##./predict_gene_expression.py --dosages dosagefile_path --dosages_prefix chr --weights prediction_db --output output

testdir = '/working-examples/test-performance-models/'
setwd('testdir')

## Arguments to be prompted
testset = 'gtex'
modelname = 'DGN-WB_0.5' ## name of the db with prediction model, without the .db
## ./predict_gene_expression.py --dosages dosages --dosages_prefix chr --weights DGN-WB_0.5.db --output output

DOSAGE_DIR = 'input/' %&% testset %&% '/genotype'
DOSAGE_PREFIX = 'chr'
BETA_FILE = 'input/models/' %&% modelname %&% '.db'
OUTPUT_FILE = 'output/' %&% testset %&% '/predicted-' %&% modelname 

predict.command = 'python scripts/predict_gene_expression.py --dosages ' %&% DOSAGE_DIR %&% ' --dosages_prefix ' %&% DOSAGE_PREFIX %&% ' --weights ' %&% BETA_FILE %&% ' --output ' %&% OUTPUT_FILE

predict.command
## uncomment to run the prediction
## system(predict.command)

```

```{r COMPARE PREDICTED VS OBSERVED}

## select = individuals and genes



## compute cor(predicted,observed)

## hist( cor(p,o) )

## plot(cor^2(p,o), cv.R2)

## 

```